controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    position_controller:
      type: position_controllers/JointGroupPositionController

    pole_controller:
      type: position_controllers/JointGroupPositionController

    

velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - foot_joint
    
position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - foot_joint

pole_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - cartpole_joint