controller_manager:
  ros__parameters:
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      gripper_action_controller:
        type: position_controllers/GripperActionController
      



gripper_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    joint: 'hande_left_finger_joint'
    max_effort: 0.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
