controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    inertia_wheel_roll_joint_velocity_controller:
      type: effort_controllers/JointGroupEffortController

inertia_wheel_roll_joint_velocity_controller:
  ros__parameters:
    joints:
      - inertia_wheel_roll_joint
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    pid: {p: 1.0, i: 0.0, d: 0.0}